
language: node_js
node_js:
  - '10'

services: 
  - docker

before_install:
  - npm update
  - npm install -g react-scripts
  - npm install -g codecov

before-script:
  - chmod +x scripts/deployServer.sh
  - chmod +x scripts/coverage.sh

script:
  - make
